Repository boostcampwm-2021/iOS09-BBus, pull requests merged in 2021-11, with the labels that each got.

#11 [뷰] 1-5. 노선도 화면이 제공되어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/BusTagMaxSize.imageset/BusTagMaxSize-1.png
  BBus/BBus/Assets.xcassets/BusTagMaxSize.imageset/BusTagMaxSize-2.png
  BBus/BBus/Assets.xcassets/BusTagMaxSize.imageset/BusTagMaxSize.png
  BBus/BBus/Assets.xcassets/BusTagMaxSize.imageset/Contents.json
  BBus/BBus/Assets.xcassets/BusTagMinSize.imageset/BusTagMinSize-1.png
  BBus/BBus/Assets.xcassets/BusTagMinSize.imageset/BusTagMinSize-2.png
  BBus/BBus/Assets.xcassets/BusTagMinSize.imageset/BusTagMinSize.png
  BBus/BBus/Assets.xcassets/BusTagMinSize.imageset/Contents.json
  BBus/BBus/Assets.xcassets/GetOff.imageset/Contents.json
  BBus/BBus/Assets.xcassets/GetOff.imageset/GetOff-1.png
  BBus/BBus/Assets.xcassets/GetOff.imageset/GetOff-2.png
  BBus/BBus/Assets.xcassets/GetOff.imageset/GetOff.png
  BBus/BBus/Assets.xcassets/GetOn.imageset/Contents.json
  BBus/BBus/Assets.xcassets/GetOn.imageset/GetOn-1.png
  BBus/BBus/Assets.xcassets/GetOn.imageset/GetOn-2.png
  BBus/BBus/Assets.xcassets/GetOn.imageset/GetOn.png
  BBus/BBus/Assets.xcassets/StationCenterCircle.imageset/Contents.json
  BBus/BBus/Assets.xcassets/StationCenterCircle.imageset/StationCenterCircle-1.png
  BBus/BBus/Assets.xcassets/StationCenterCircle.imageset/StationCenterCircle-2.png
  BBus/BBus/Assets.xcassets/StationCenterCircle.imageset/StationCenterCircle.png
  BBus/BBus/Assets.xcassets/Uturn.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Uturn.imageset/Uturn-1.png
  BBus/BBus/Assets.xcassets/Uturn.imageset/Uturn-2.png
  BBus/BBus/Assets.xcassets/Uturn.imageset/Uturn.png
  BBus/BBus/Assets.xcassets/busIcon.imageset/Contents.json
  BBus/BBus/Assets.xcassets/busIcon.imageset/busIcon-1.png
  BBus/BBus/Assets.xcassets/busIcon.imageset/busIcon-2.png
  BBus/BBus/Assets.xcassets/busIcon.imageset/busIcon.png
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/View/BusRouteHeaderView.swift
  BBus/BBus/BusRoute/View/BusRouteView.swift
  BBus/BBus/BusRoute/View/BusStationTableViewCell.swift
  BBus/BBus/BusRoute/View/BusTagView.swift
  BBus/BBus/BusRoute/View/CustomNavigationBar.swift
Labels: 👍 review

#14 [뷰] 1-5. 노선도 화면이 제공되어야 한다.
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
Labels: 👍 review

#13 [뷰] 1-6. 알람 설정 화면이 제공되어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingButton.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/AlarmSetting/View/GetOffTableViewCell.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/Assets.xcassets/alarmIconGrayColor.colorset/Contents.json
  BBus/BBus/Assets.xcassets/alarmOff.imageset/Contents.json
  BBus/BBus/Assets.xcassets/alarmOff.imageset/alarmOff-1.png
  BBus/BBus/Assets.xcassets/alarmOff.imageset/alarmOff-2.png
  BBus/BBus/Assets.xcassets/alarmOff.imageset/alarmOff.png
  BBus/BBus/Assets.xcassets/alarmOn.imageset/Contents.json
  BBus/BBus/Assets.xcassets/alarmOn.imageset/alarmOn-1.png
  BBus/BBus/Assets.xcassets/alarmOn.imageset/alarmOn-2.png
  BBus/BBus/Assets.xcassets/alarmOn.imageset/alarmOn.png
  BBus/BBus/Assets.xcassets/grayBusIcon.imageset/Contents.json
  BBus/BBus/Assets.xcassets/grayBusIcon.imageset/grayBusIcon-1.png
  BBus/BBus/Assets.xcassets/grayBusIcon.imageset/grayBusIcon-2.png
  BBus/BBus/Assets.xcassets/grayBusIcon.imageset/grayBusIcon.png
  BBus/BBus/Assets.xcassets/locationIcon.imageset/Contents.json
  BBus/BBus/Assets.xcassets/locationIcon.imageset/locationIcon-1.png
  BBus/BBus/Assets.xcassets/locationIcon.imageset/locationIcon-2.png
  BBus/BBus/Assets.xcassets/locationIcon.imageset/locationIcon.png
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift
  BBus/BBus/BusRoute/View/BusRouteView.swift
  BBus/BBus/BusRoute/View/BusStationTableViewCell.swift
  BBus/BBus/Coordinator/MovingStatusPushable.swift
  BBus/BBus/MovingStatus/MovingStatusCoordinator.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
Labels: 👍 review

#15 [뷰] 1-2, 1-3. 검색 화면(버스)/(정거장)이 제공되어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/bbusSearchRed.colorset/Contents.json
  BBus/BBus/Coordinator/SearchBusPushable.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/HomeView.swift
  BBus/BBus/SearchBus/Model/SearchModel.swift
  BBus/BBus/SearchBus/SearchBusViewController.swift
  BBus/BBus/SearchBus/SearchCoordinator.swift
  BBus/BBus/SearchBus/SearchViewController.swift
  BBus/BBus/SearchBus/UseCase/SearchUseCase.swift
  BBus/BBus/SearchBus/View/KeyboardAccessoryView.swift
  BBus/BBus/SearchBus/View/SearchBusView.swift
  BBus/BBus/SearchBus/View/SearchNavigationView.swift
  BBus/BBus/SearchBus/View/SearchResultCollectionViewCell.swift
  BBus/BBus/SearchBus/View/SearchResultHeaderView.swift
  BBus/BBus/SearchBus/View/SearchResultScrollView.swift
  BBus/BBus/SearchBus/View/SearchView.swift
  BBus/BBus/SearchBus/ViewModel/SearchViewModel.swift
  BBus/BBus/SearchStation/Model/SearchStationModel.swift
  BBus/BBus/SearchStation/SearchStationViewController.swift
  BBus/BBus/SearchStation/UseCase/SearchStationUseCase.swift
  BBus/BBus/SearchStation/View/SearchStationView.swift
  BBus/BBus/SearchStation/ViewModel/SearchStationViewModel.swift
Labels: 👍 review

#21 [뷰] 1-4. 정거장 화면이 제공되어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/bbusLikeYellow.colorset/Contents.json
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/BusCellTrailingView.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Home/View/HomeView.swift
  BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift
  BBus/BBus/Search/Model/SearchModel.swift
  BBus/BBus/Search/SearchCoordinator.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Search/View/KeyboardAccessoryView.swift
  BBus/BBus/Search/View/SearchNavigationView.swift
  BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
  BBus/BBus/Search/View/SearchResultScrollView.swift
  BBus/BBus/Search/View/SearchView.swift
  BBus/BBus/Search/View/SimpleCollectionHeaderView.swift
  BBus/BBus/Search/ViewModel/SearchViewModel.swift
  BBus/BBus/Station/StationCoodinator.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
  BBus/BBus/Station/View/StationHeaderView.swift
  BBus/BBus/Station/View/StationView.swift
Labels: 👍 review

#22 [뷰] 1-7. 이동 현황 화면이 제공되어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/BooDuck.imageset/BooDuck-1.png
  BBus/BBus/Assets.xcassets/BooDuck.imageset/BooDuck-2.png
  BBus/BBus/Assets.xcassets/BooDuck.imageset/BooDuck.png
  BBus/BBus/Assets.xcassets/BooDuck.imageset/Contents.json
  BBus/BBus/Assets.xcassets/BusIconWithBooDuck.imageset/BusIconWithBooDuck-1.png
  BBus/BBus/Assets.xcassets/BusIconWithBooDuck.imageset/BusIconWithBooDuck-2.png
  BBus/BBus/Assets.xcassets/BusIconWithBooDuck.imageset/BusIconWithBooDuck.png
  BBus/BBus/Assets.xcassets/BusIconWithBooDuck.imageset/Contents.json
  BBus/BBus/Assets.xcassets/SpeechBubble.imageset/Contents.json
  BBus/BBus/Assets.xcassets/SpeechBubble.imageset/SpeechBubble-1.png
  BBus/BBus/Assets.xcassets/SpeechBubble.imageset/SpeechBubble-2.png
  BBus/BBus/Assets.xcassets/SpeechBubble.imageset/SpeechBubble.png
  BBus/BBus/MovingStatus/MovingStatusCoordinator.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift
  BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/SceneDelegate.swift
Labels: 👍 review

#35 [리팩토링] Coordinator 패턴을 현재 앱 상황에 맞게 개선
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Assets.xcassets/Color/bbusGray6.colorset/Contents.json
  BBus/BBus/Assets.xcassets/Image/booDuck.imageset/BooDuck-1.png
  BBus/BBus/Assets.xcassets/Image/booDuck.imageset/BooDuck-2.png
  BBus/BBus/Assets.xcassets/Image/booDuck.imageset/BooDuck.png
  BBus/BBus/Assets.xcassets/Image/booDuck.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/speechBubble.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/speechBubble.imageset/SpeechBubble-1.png
  BBus/BBus/Assets.xcassets/Image/speechBubble.imageset/SpeechBubble-2.png
  BBus/BBus/Assets.xcassets/Image/speechBubble.imageset/SpeechBubble.png
  BBus/BBus/Assets.xcassets/Image/stationCenterCircle.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/stationCenterCircle.imageset/StationCenterCircle-1.png
  BBus/BBus/Assets.xcassets/Image/stationCenterCircle.imageset/StationCenterCircle-2.png
  BBus/BBus/Assets.xcassets/Image/stationCenterCircle.imageset/StationCenterCircle.png
  BBus/BBus/Assets.xcassets/Image/uturn.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/uturn.imageset/Uturn-1.png
  BBus/BBus/Assets.xcassets/Image/uturn.imageset/Uturn-2.png
  BBus/BBus/Assets.xcassets/Image/uturn.imageset/Uturn.png
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/View/CustomNavigationBar.swift
  BBus/BBus/Global/Constant/BBusColor.swift
  BBus/BBus/Global/Coordinator/AlarmSettingPushable.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/BusRoutePushable.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/MovingStatusPushable.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/Global/Coordinator/SearchBusPushable.swift
  BBus/BBus/Global/Coordinator/StationPushable.swift
  BBus/BBus/Home/HomeCoornicator.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/HomeNavigationView.swift
  BBus/BBus/Home/View/HomeView.swift
  BBus/BBus/MovingStatus/MovingStatusCoordinator.swift
  BBus/BBus/MovingStatus/MovingStatusFoldUnfoldDelegate.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/SceneDelegate.swift
  BBus/BBus/Search/SearchCoordinator.swift
  BBus/BBus/Station/StationCoodinator.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
Labels: 🧱 refactor

#37 [네트워크] 0-1~5. BBusAPIUsecase단, Fetcher단, Service, Persistent 구조를 지닌 네트워크를 구현한다.
  .github/workflows/swift.yml
  .gitignore
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteItemFetchable.swift
  BBus/BBus/Global/Network/Fetcher/GetArrInfoByRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetBusPosByRtidFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetFavoriteItemListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteInfoItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationByUidItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByPosListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
  BBus/BBus/Global/Network/Persistent.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Info.plist
Labels: 👍 review

#41 [네트워크] 0-6. 결과로 넘어온 XML를 DTO로 반환할 수 있어야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Global/ArrInfoByRouteDTO.swift
  BBus/BBus/Global/BBusXMLDTO.swift
  BBus/BBus/Global/BusPosByRtidDTO.swift
  BBus/BBus/Global/StationByRouteListDTO.swift
  BBus/BBus/Global/StationByUidItemDTO.swift
  BBus/BBus/Global/StationsByPosDTO.swift
  BBus/BBus/Global/XMLParser/BBusXMLParser.swift
  BBus/BBus/Home/HomeViewController.swift
Labels: 👍 review

#55 [검색] 2-4. 셀을 터치하면 노선도 화면으로 이동해야 한다.
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Station/StationViewController.swift
Labels: 👍 review

#70 [버스 노선도 정보] 7-1. 특정 버스 노선 id를 통해 xml 파일을 얻어올 수 있어야 한다
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
Labels: 👍 review

#75 #72 비동기 관련 문제 스레드 동기화 하여 적용
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteItemFetchable.swift
  BBus/BBus/Global/Network/Fetcher/GetArrInfoByRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetBusPosByRtidFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetFavoriteItemListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteInfoItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationByUidItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByPosListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
  BBus/BBus/Global/Network/Persistent.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/Search/SearchCoordinator.swift
Labels: 👍 review

#78 [정거장 정보] 4-1. 상단 헤더에 버스 ID, 정거장명, 정거장 방향이 표시된다.
  BBus/BBus/Global/DTO/StationByUidItemDTO.swift
  BBus/BBus/Global/Network/Persistent.swift
  BBus/BBus/Station/StationCoodinator.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/UseCase/StationUseCase.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#82 [버스 노선도 정보] 7-4. 셀에는 정거장 명, 정거장 번호, 첫차~종착 시간이 표시된다.
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift
  BBus/BBus/BusRoute/View/BusRouteView.swift
  BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Global/DTO/StationByRouteListDTO.swift
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
Labels: 👍 review, ✅ 리뷰완료

#88 [검색] 3-6. 얻어온 정거장의 이름 또는 번호와 일치하는 부분을 주황색으로 표시한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Search/Model/BusSearchResult.swift
  BBus/BBus/Search/Model/SearchResults.swift
  BBus/BBus/Search/Model/StationSearchResult.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
  BBus/BBus/Search/ViewModel/SearchViewModel.swift
Labels: 👍 review, ✅ 리뷰완료

#97 [정거장 정보] 4-3. 버스 목록에서 도착정보가 하나도 없는 버스는 가장 아래쪽에 보여져야 한다.
  BBus/BBus/Home/View/BusCellTrailingView.swift
  BBus/BBus/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift
  BBus/BBus/Station/StationCoodinator.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/UseCase/StationUseCase.swift
  BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
  BBus/BBus/Station/View/StationHeaderView.swift
  BBus/BBus/Station/View/StationView.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#93 [즐겨찾기] 14-1. 즐겨찾기 목록은 정류장 종류 별로 정렬되어 보여져야 한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Global/DTO/FavoriteItemDTO.swift
  BBus/BBus/Global/DTO/FavoriteOrderDTO.swift
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteOrderFetcher.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteItemFetchable.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteOrder.swift
  BBus/BBus/Global/Network/Fetcher/GetFavoriteOrder.swift
  BBus/BBus/Global/Network/Persistent.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
  BBus/BBus/Home/HomeCoordinator.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/Model/HomeModel.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/HomeView.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
Labels: 👍 review

#117 [버스 노선도 정보] 8-1. 새로고침 버튼을 누르면 자동 갱신과 별도로 데이터를 새로 받아온다.
  BBus/BBus/BusRoute/BusRouteViewController.swift
Labels: 👍 review

#135 [승하차 알람] 11-5. 상단에는 버스 종류에 해당하는 색상으로 버스 번호를 표시하고, 그 아래에는 몇 정거장이 남았는지와 소요 예정 시간을 표시한다.
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/UseCase/MovingStatusUseCase.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 👍 review

#132 [리팩토링] 14-1 FavoriteOrder 제거
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Global/DTO/FavoriteOrderDTO.swift
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteOrderFetcher.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteOrder.swift
  BBus/BBus/Global/Network/Fetcher/GetFavoriteOrder.swift
  BBus/BBus/Global/Network/Persistent.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
  BBus/BBus/Home/Model/HomeModel.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
Labels: 👍 review, ✅ 리뷰완료

#134 [버그 FIX] 검색 결과가 나오지 않는 버그 해결
  BBus/BBus/Search/UseCase/SearchUseCase.swift
Labels: 👍 review

#136 [승하차 알람] 9-1 가장 가까운 2개 버스에 대해 남은 시간/정류장, 도착 예정 시간, 버스가 위치한 정류장, 버스 일련번호가 표시된다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
  BBus/BBus/AlarmSetting/Model/AlarmSettingModel.swift
  BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#144 [리뷰 반영] #97 리뷰 반영 및 CollectionView height 수정
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Home/View/BusCellTrailingView.swift
  BBus/BBus/Station/Model/BusCongestion.swift
  BBus/BBus/Station/Model/BusRemainTime.swift
  BBus/BBus/Station/Model/StationModel.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/View/StationView.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 😎 리뷰 반영

#145 [리뷰 반영] BusRouteViewController 리뷰반영 및 weak self, final 추가 작업
  BBus/BBus/Assets.xcassets/Color/bbusCongestionLow.colorset/Contents.json
  BBus/BBus/Assets.xcassets/Color/bbusCongestionMedium.colorset/Contents.json
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/BusRoute/View/BusRouteTableViewCell.swift
  BBus/BBus/BusRoute/View/BusRouteView.swift
  BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Global/Constant/BBusColor.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 🖋 restyle, 😎 리뷰 반영

#151 [리뷰 반영] XML Parser 리뷰 코드 반영
  BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift
  BBus/BBus/Global/DTO/BBusXMLDTO.swift
  BBus/BBus/Global/DTO/BusPosByRtidDTO.swift
  BBus/BBus/Global/DTO/StationByRouteListDTO.swift
  BBus/BBus/Global/DTO/StationByUidItemDTO.swift
  BBus/BBus/Global/DTO/StationsByPosDTO.swift
  BBus/BBus/Global/XMLParser/BBusXMLParser.swift
Labels: 😎 리뷰 반영

#153 [리뷰 반영] 정거장 검색 리뷰 코드 반영
  BBus/BBus/Search/SearchCoordinator.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Search/ViewModel/SearchViewModel.swift
Labels: 😎 리뷰 반영

#155 [리뷰 반영] final 처리 - 검색 화면
  BBus/BBus/Search/SearchCoordinator.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Search/View/KeyboardAccessoryView.swift
  BBus/BBus/Search/View/SearchNavigationView.swift
  BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
  BBus/BBus/Search/View/SearchResultScrollView.swift
  BBus/BBus/Search/View/SearchView.swift
  BBus/BBus/Search/View/SimpleCollectionHeaderView.swift
  BBus/BBus/Search/ViewModel/SearchViewModel.swift
Labels: 😎 리뷰 반영

#148 [즐겨찾기] 14-3. 헤더를 누르면 알맞는 정거장 화면으로 이동한다.
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/HomeView.swift
Labels: 👍 review

#156 [즐겨찾기] 14-5. 셀에는 해당 정거장의 버스 도착 정보를 표시한다.
  BBus/BBus/Global/Constant/BBusRouteType.swift
  BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/Home/HomeCoordinator.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/Model/HomeModel.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
Labels: 👍 review

#157 [즐겨찾기] 14-9. 셀의 알람 버튼을 누르면 알람 설정 화면으로 이동한다.
  BBus/BBus/Home/HomeViewController.swift
Labels: 👍 review

#159 [승하차 알람] 9-2 도착정보가 없으면 표시하지 않고, 남은 시간은 API가 보낸 메세지를 그대로 띄운다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/Global/Extension/UIViewExtension.swift
Labels: 👍 review

#161 [승하차 알람] 9-2. 도착정보가 없으면 표시하지 않고, 남은 시간은 API가 보낸 메세지를 그대로 띄운다.2
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/AlarmSetting/View/NoneInfoTableViewCell.swift
  BBus/BBus/Global/Constant/BBusImage.swift
  BBus/BBus/Global/Network/AccessKey.xcconfig
  BBus/BBus/Global/Network/Service.swift
Labels: 👍 review

#162 [갱신] 17-1. 남은 정류소 시간을 보여주는 모든 화면에 대해 1초 간격으로 줄어드는 뷰를 보여준다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Global/Extension/NotificationNameExtension.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/Model/HomeModel.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/SceneDelegate.swift
  BBus/BBus/Station/Model/BusRemainTime.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#165 [리뷰 반영] 검색화면 버스 색상 조정
  BBus/BBus/Search/View/SearchResultCollectionViewCell.swift
Labels: 😎 리뷰 반영

#166 [승하차 알람] 11-1. 노선에 현재 유저의 위치를 표시한다.
  BBus/BBus/Global/DTO/BusPosByRtidDTO.swift
  BBus/BBus/Global/DTO/StationByRouteListDTO.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/UseCase/MovingStatusUseCase.swift
  BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift
  BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 👍 review

#170 [승하차 알람] 11-2. 노선도에는 구간 단위로 현재 교통 혼잡도가 색상(빨/노/초)으로 표시되어야 한다.
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 👍 review

#175 [즐겨찾기] 14-7. 새로고침시 버스 도착 정보를 갱신한다.
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/HomeView.swift
Labels: 👍 review

#173 fix: #167 승차 알람 섹션만 매 초마다 갱신하는 방식으로 변경
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
Labels: 👍 review

#178 [승하차 알람] 10-1~2. 정거장 셀에는 정거장 명 / 정거장 ID / 승차 지점으로부터의 소요 시간이 표시되어야 한다.
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
  BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#179 [승하차 알람] 10-3. 정거장 셀의 알람 버튼을 터치하면 실시간 이동 현황 화면으로 전환되어야 한다.
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/AlarmSetting/View/GetOffTableViewCell.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/MovingStatus/MovingStatusFoldUnfoldDelegate.swift
Labels: 👍 review

#181 [승하차 알람] 11-4. 1정거장 전부터는 "이번에 내리세요" 라는 메세지가 말풍선 아이콘에 표시되어야 한다.
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
Labels: 👍 review

#182 [승하차 알람] 9-7. 1번째 전 정거장에 버스가 위치할 경우 알람 등록이 되지 않으며 "버스가 곧 도착합니다"라는 메시지를 띄운다.
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
Labels: 👍 review

#187 design: #186 네비게이션 바에 버스 번호와 정거장 이름 뜨도록 설정
  BBus/BBus/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/BusRoute/View/CustomNavigationBar.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Station/StationViewController.swift
Labels: 👍 review

#220 [데모] 트래픽 초과를 방지하기 위해 API 요청 횟수를 인당 300회로 제한한다.
  BBus/BBus/Global/Network/Service.swift
Labels: 👍 review

#199 [리뷰 반영] #166 11-1. 노선에 현재 유저의 위치를 표시한다.
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/View/MovingStatusBusTagView.swift
  BBus/BBus/MovingStatus/View/MovingStatusTableViewCell.swift
  BBus/BBus/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 😎 리뷰 반영

#206 [리뷰 반영] 즐겨찾기 관련 리뷰 반영사항 적용
  BBus/BBus/Home/HomeCoordinator.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/Model/HomeModel.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
Labels: 😎 리뷰 반영

#216 [즐겨찾기, 검색] 제공되는 데이터가 없을 시 없다는 것을 유저에게 보여주기
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/Image/homeFavoriteEmpty.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/homeFavoriteEmpty.imageset/homeFavoriteEmpty-1.jpeg
  BBus/BBus/Assets.xcassets/Image/homeFavoriteEmpty.imageset/homeFavoriteEmpty-2.jpeg
  BBus/BBus/Assets.xcassets/Image/homeFavoriteEmpty.imageset/homeFavoriteEmpty.jpeg
  BBus/BBus/Global/Constant/BBusImage.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/View/EmptyFavoriteNoticeView.swift
  BBus/BBus/Home/View/HomeView.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/View/EmptySearchResultNoticeView.swift
  BBus/BBus/Search/View/SearchNavigationView.swift
  BBus/BBus/Search/View/SearchResultScrollView.swift
  BBus/BBus/Search/View/SearchView.swift
Labels: 👍 review

#207 [리뷰 반영] 승차 알람 도착 정보 표시 관련 리뷰 반영
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
Labels: 🖋 restyle, 😎 리뷰 반영

#211 [리뷰 반영] PresentAlert 관련 수정
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
Labels: 🖋 restyle, 😎 리뷰 반영

#223 [정거장 정보] 정거장 화면 정보 안뜸 에러
  BBus/BBus/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/Home/View/RemainCongestionBadgeLabel.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 🐛 fix

#226 [즐겨찾기] FavoriteItemList가 무한 fetch되어 메모리 사용량이 계속 증가하는 현상
  BBus/BBus/Global/Network/Persistent.swift
Labels: 👍 review

#227 [승하차 알람] 11-6. 하차 정거장에 도착할 경우 "알람이 종료됩니다"라는 Alert 메세지를 띄우고 알람이 자동 종료된다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/Coordinator/Pushables.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Info.plist
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Station/StationViewController.swift
Labels: 👍 review

#228 [정거장 정보] 마을버스 클릭시 앱이 죽는 현상
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/UseCase/StationUseCase.swift
Labels: 👍 review

#231 [버그] Issue/#33
  BBus/BBus/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/AlarmSetting/View/GetOffTableViewCell.swift
  BBus/BBus/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/BusRoute/BusRouteViewController.swift
  BBus/BBus/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Global/View/CustomNavigationBar.swift
  BBus/BBus/Home/HomeCoordinator.swift
  BBus/BBus/Home/HomeViewController.swift
  BBus/BBus/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Home/View/BusCellTrailingView.swift
  BBus/BBus/Home/View/FavoriteCollectionHeaderView.swift
  BBus/BBus/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Home/View/HomeNavigationView.swift
  BBus/BBus/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/MovingStatus/UseCase/MovingStatusUseCase.swift
  BBus/BBus/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Search/SearchCoordinator.swift
  BBus/BBus/Search/SearchViewController.swift
  BBus/BBus/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Search/View/EmptySearchResultNoticeView.swift
  BBus/BBus/Search/View/KeyboardAccessoryView.swift
  BBus/BBus/Search/View/SearchNavigationView.swift
  BBus/BBus/Search/ViewModel/SearchViewModel.swift
  BBus/BBus/Station/StationCoodinator.swift
  BBus/BBus/Station/StationViewController.swift
  BBus/BBus/Station/UseCase/StationUseCase.swift
  BBus/BBus/Station/View/StationBodyCollectionViewCell.swift
  BBus/BBus/Station/ViewModel/StationViewModel.swift
Labels: 🐛 fix

#233 [리뷰 반영] 즐겨찾기 버튼 터치가 씹히는 현상 리뷰 반영
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/Model/AlarmSettingBusArriveInfos.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
Labels: 😎 리뷰 반영

#247 [메모리 누수] coordinator.terminate() 하여도 각 ViewController 및 하위 뷰들은 메모리에 남아있다.
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/View/GetOffTableViewCell.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Foreground/Home/View/HomeNavigationView.swift
  BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusUseCase.swift
  BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Foreground/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift
  BBus/BBus/Global/View/CustomNavigationBar.swift
Labels: 👍 review

#250 [정거장 정보] 즐겨찾기 추가/해제 시 화면이 깜빡이는 현상
  BBus/BBus/Foreground/Station/StationViewController.swift
Labels: 👍 review

#240 [리뷰 반영] #227 11-6. 하차 정거장에 도착할 경우 "알람이 종료됩니다"라는 Alert 메세지를 띄우고 알람이 자동 종료된다.
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
  BBus/BBus/Info.plist
Labels: 👍 review, 😎 리뷰 반영

#255 [갱신] 무한 push로 쌓인 화면들에서도 자동갱신 때문에 api를 요청하는 문제
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
Labels: 🧱 refactor, 👍 review

#235 [리뷰 반영] #221 리뷰 반영
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Global/Extension/PublisherExtension.swift
  BBus/BBus/Global/Network/Service.swift
Labels: 😎 리뷰 반영

#239 [리뷰 반영] 9-11. 어느 화면에서든 승차 알람을 받을 수 있도록 하는 객체가 필요하다.
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/Model/GetOnAlarmStatus.swift
  BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmUsecase.swift
  BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift
  BBus/BBus/GetOnAlarmDelegate.swift
  BBus/BBus/Global/DTO/BBusXMLDTO.swift
  BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift
  BBus/BBus/Global/Extension/PublisherExtension.swift
Labels: 😎 리뷰 반영

#251 [승하차 알람] 9-4. 알람 버튼을 클릭하면 알람이 설정된다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Assets.xcassets/Image/alarmOnTint.imageset/Contents.json
  BBus/BBus/Assets.xcassets/Image/alarmOnTint.imageset/alarmOnTint-1.png
  BBus/BBus/Assets.xcassets/Image/alarmOnTint.imageset/alarmOnTint-2.png
  BBus/BBus/Assets.xcassets/Image/alarmOnTint.imageset/alarmOnTint.png
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/Model/GetOnAlarmStatus.swift
  BBus/BBus/Background/GetOnAlarm/Model/GetOnStartResult.swift
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/Model/AlarmSettingBusArriveInfo.swift
  BBus/BBus/Foreground/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/View/BusCellTrailingView.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Global/Constant/BBusImage.swift
  BBus/BBus/Global/Extension/StringExtension.swift
Labels: 🧰 feature, 👍 review

#256 [승하차 알람] 다른 지역 버스에 대해 승하차 알람 화면 진입시 하차 알람 섹션이 뜨지 않음
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/Model/AlarmSettingBusArriveInfos.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
Labels: 👍 review

#258 [앵플라맹스] 새로고침 버튼 하차 알람 설정에 따라 위치 조정
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
Labels: 🖋 restyle, 👍 review

#264 [버그] 하차알림 페이지 알람 버튼 클릭 시 화면 height관련 에러 해결
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
Labels: 🐛 fix, 👍 review

#269 [네트워크] MapJSONBBusError operator 완성하기
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift
  BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift
  BBus/BBus/Global/Extension/PublisherExtension.swift
Labels: 🧰 feature, 👍 review

#268 [갱신] 1초 타이머에서 2초씩 깎이는 현상
  BBus/BBus/Foreground/Home/HomeViewController.swift
Labels: 👍 review

#272 [네트워크] XML 파서 -> JSON 객체로 수정
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusUseCase.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift
  BBus/BBus/Global/DTO/ArrInfoByRouteDTO.swift
  BBus/BBus/Global/DTO/BBusXMLDTO.swift
  BBus/BBus/Global/DTO/BusPosByRtidDTO.swift
  BBus/BBus/Global/DTO/StationByRouteListDTO.swift
  BBus/BBus/Global/DTO/StationByUidItemDTO.swift
  BBus/BBus/Global/DTO/StationsByPosDTO.swift
  BBus/BBus/Global/Extension/PublisherExtension.swift
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/GetArrInfoByRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetBusPosByRtidFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteInfoItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationByUidItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByPosListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
  BBus/BBus/Global/XMLParser/BBusXMLParser.swift
Labels: 🧱 refactor

#276 fix: #275 하차 알람 관련 버그 해결
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
Labels: 👍 review

#280 [즐겨찾기] 로컬 json에 없는 버스는 홈화면에 정보가 안뜨는 버그
  BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift
Labels: 👍 review

#284 [리뷰 반영] 다른 지역 버스에 대해 승하차 알람 화면 진입시 하차 알람 섹션이 뜨지 않음
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingUseCase.swift
Labels: 😎 리뷰 반영

#281 [리뷰 반영] 백그라운드 리뷰 & MapJSONBBusError operator 리뷰 반영
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift
Labels: 🖋 restyle

#289 [정거장 정보] 마지막 셀의 알람 버튼을 누를 수 없다
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/View/EmptyFavoriteNoticeView.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Foreground/Home/View/HomeView.swift
  BBus/BBus/Foreground/Home/View/SourceFooterView.swift
  BBus/BBus/Foreground/Station/View/StationView.swift
Labels: 🐛 fix, 👍 review

#288 [데이터 로딩] 16-1. 각 화면에서 네트워크 요청에 대해 response가 오기 전까지 로더를 보여준다
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
  BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/View/StationView.swift
  BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#287 [정거장 정보] ViewModel의 Collection 로 선언되어있는 property를 일급 컬렉션으로 추상화한다.
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Station/Model/BusArriveInfos.swift
  BBus/BBus/Foreground/Station/Model/BusSectionKeys.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
Labels: 👍 review

#291 [커스텀 Cell] prepareForReuse 내의 cancellable cancel() 로직 제거
  BBus/BBus/Foreground/AlarmSetting/View/GetOffTableViewCell.swift
  BBus/BBus/Foreground/AlarmSetting/View/GetOnStatusCell.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
Labels: 👍 review

#304 [리팩토링] AlarmSetting 화면 UseCase 리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
Labels: 🧱 refactor

#305 [리펙토링] BusRouteUsecase 화면 UseCase 리펙토링
  BBus/BBus/Foreground/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
Labels: 🧱 refactor

#308 [리팩토링] 홈화면 UseCase리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Home/HomeCoordinator.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
  BBus/BBus/Foreground/Home/UseCase/HomeUseCase.swift
  BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
Labels: 🧱 refactor

#311 [리펙토링] MovingStatusViewModel 로직을 UseCase 로 이동
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingCalculateUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusCalculateUseCase.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/UseCase/AverageSectionTimeCalculatable.swift
Labels: 🧱 refactor, 👍 review

#313 [리팩토링] AlarmSettingViewModel의 useCase 타입 변경
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/ViewModel/AlarmSettingViewModel.swift
Labels: 🧱 refactor

#314 [리팩토링] Station 화면 UseCase 리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Station/StationCoordinator.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift
  BBus/BBus/Foreground/Station/UseCase/StationCalculateUseCase.swift
  BBus/BBus/Foreground/Station/UseCase/StationUseCase.swift
  BBus/BBus/Foreground/Station/ViewModel/StationViewModel.swift
  BBus/BBus/Global/Network/BBusAPIError.swift
Labels: 🧱 refactor, 👍 review

#318 [리팩토링] Search 화면 UseCase 리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Search/SearchCoordinator.swift
  BBus/BBus/Foreground/Search/SearchViewController.swift
  BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift
  BBus/BBus/Foreground/Search/UseCase/SearchCalculateUseCase.swift
  BBus/BBus/Foreground/Search/UseCase/SearchUseCase.swift
  BBus/BBus/Foreground/Search/ViewModel/SearchViewModel.swift
Labels: 🧱 refactor, 👍 review

#315 [리펙토링] HomeViewController: BaseViewController 채택
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Global/Base/BaseViewController.swift
Labels: 🧱 refactor, 👍 review

#317 [리팩토링] 새로고침 버튼, Navigation Bar를 각 화면의 view 내에 속하게 수정
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/View/HomeView.swift
  BBus/BBus/Global/CustomView/NavigatableView.swift
  BBus/BBus/Global/CustomView/RefreshButton.swift
  BBus/BBus/Global/CustomView/RefreshableView.swift
  BBus/BBus/Global/CustomView/ThrottleButton.swift
Labels: 🧱 refactor, 👍 review

#316 [리팩토링] 홈화면 UseCase리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmAPIUsecase.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/Home/HomeCoordinator.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
  BBus/BBus/Foreground/Home/UseCase/HomeCalculateUseCase.swift
  BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
Labels: 🧱 refactor, 👍 review

#310 [리팩토링] Service 리팩토링
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmAPIUsecase.swift
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingCoordinator.swift
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
  BBus/BBus/Foreground/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/Home/HomeCoordinator.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusCalculateUseCase.swift
  BBus/BBus/Foreground/Search/SearchCoordinator.swift
  BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift
  BBus/BBus/Foreground/Station/StationCoordinator.swift
  BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Extension/PublisherExtension.swift
  BBus/BBus/Global/Network/BBusAPIUseCases.swift
  BBus/BBus/Global/Network/BBusAPIUsecases.swift
  BBus/BBus/Global/Network/Fetcher/CreateFavoriteItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/DeleteFavoriteItemFetchable.swift
  BBus/BBus/Global/Network/Fetcher/GetArrInfoByRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetBusPosByRtidFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetBusPosByVehIdFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetFavoriteItemListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteInfoItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationByUidItemFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/GetStationsByRouteListFetcher.swift
  BBus/BBus/Global/Network/Fetcher/PersistencetFetchable.swift
  BBus/BBus/Global/Network/Fetcher/ServiceFetchable.swift
  BBus/BBus/Global/Network/NetworkService.swift
  BBus/BBus/Global/Network/PersistenceStorage.swift
  BBus/BBus/Global/Network/PersistentStorage.swift
  BBus/BBus/Global/Network/RequestFactory.swift
  BBus/BBus/Global/Network/RequestUseCases/CreateFavoriteItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/DeleteFavoriteItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetArrInfoByRouteListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetBusPosByRtidUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetBusPosByVehIdUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetFavoriteItemListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetRouteListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationByUidItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationsByRouteListUsable.swift
  BBus/BBus/Global/Network/RequestUsecases.swift
  BBus/BBus/Global/Network/Service.swift
  BBus/BBus/Global/Network/TokenManager.swift
Labels: 🧱 refactor

#320 [리팩토링] 홈 화면 Status Bar 접근 로직 리팩토링
  BBus/BBus/Foreground/Home/HomeCoordinator.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
  BBus/BBus/Global/Coordinator/Coordinator.swift
Labels: 🧱 refactor, 👍 review

#323 [리펙토링] BaseViewController 생성
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
  BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
  BBus/BBus/Foreground/Home/HomeViewController.swift
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/Foreground/Search/SearchViewController.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/View/StationView.swift
  BBus/BBus/Global/CustomView/CustomNavigationBar.swift
  BBus/BBus/Global/CustomView/RefreshableView.swift
Labels: 🧱 refactor, 👍 review

#324 [버그] 가로모드 지원 제한 & 다크모드 로더 색상 변경
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
  BBus/BBus/Foreground/Home/View/FavoriteCollectionViewCell.swift
  BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/Foreground/Station/View/StationView.swift
  BBus/BBus/Info.plist
Labels: 🧱 refactor

#326 [리펙토링] BusRouteViewModel, MovingStatusViewModel - UseCase -> Useable 타입으로 수정
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
Labels: 🧱 refactor

#325 [리팩토링, 버그] UserNotification을 담당하는 객체 분리 및 권한 허용되어있지 않을 시 환경설정으로 넘어가기
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Background/GetOffAlarm/GetOffAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/ViewModel/MovingStatusViewModel.swift
  BBus/BBus/Global/DeviceConfig/AlarmCenter.swift
Labels: 🐛 fix, 🧱 refactor, 👍 review

#327 [홈 화면 버그] cancellable이 동시접근되는 이슈
  BBus/BBus/Foreground/Home/Model/HomeModel.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
  BBus/BBus/Foreground/Home/ViewModel/HomeViewModel.swift
Labels: 👍 review

#328 [리팩토링] 새로고침 버튼, Navigation Bar를 각 화면의 view 내에 속하게 수정
  BBus/BBus/Foreground/AlarmSetting/AlarmSettingViewController.swift
  BBus/BBus/Foreground/AlarmSetting/View/AlarmSettingView.swift
  BBus/BBus/Foreground/BusRoute/BusRouteViewController.swift
  BBus/BBus/Foreground/BusRoute/View/BusRouteView.swift
  BBus/BBus/Foreground/Home/View/HomeView.swift
  BBus/BBus/Foreground/MovingStatus/MovingStatusViewController.swift
  BBus/BBus/Foreground/MovingStatus/View/MovingStatusView.swift
  BBus/BBus/Foreground/Station/StationViewController.swift
  BBus/BBus/Foreground/Station/View/StationView.swift
  BBus/BBus/Global/CustomView/CustomNavigationBar.swift
  BBus/BBus/Global/CustomView/NavigatableView.swift
  BBus/BBus/Global/CustomView/RefreshButton.swift
  BBus/BBus/Global/CustomView/RefreshableView.swift
Labels: 🧱 refactor, 👍 review

#329 [리팩토링] usecase → useCase로 통일
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Background/GetOnAlarm/GetOnAlarmController.swift
  BBus/BBus/Background/GetOnAlarm/UseCase/GetOnAlarmAPIUseCase.swift
  BBus/BBus/Background/GetOnAlarm/ViewModel/GetOnAlarmViewModel.swift
  BBus/BBus/Foreground/BusRoute/BusRouteCoordinator.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteUseCase.swift
  BBus/BBus/Foreground/BusRoute/ViewModel/BusRouteViewModel.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift
  BBus/BBus/Foreground/Search/SearchCoordinator.swift
  BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift
  BBus/BBus/Foreground/Station/StationCoordinator.swift
  BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift
  BBus/BBus/Global/Coordinator/AppCoordinator.swift
Labels: 🖋 restyle

#333 [리팩토링] 프로토콜과 extension 파일 분리
  BBus/BBus.xcodeproj/project.pbxproj
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUsable.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingAPIUseCase.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingCalculatable.swift
  BBus/BBus/Foreground/AlarmSetting/UseCase/AlarmSettingCalculateUseCase.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteAPIUsable.swift
  BBus/BBus/Foreground/BusRoute/UseCase/BusRouteAPIUseCase.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUsable.swift
  BBus/BBus/Foreground/Home/UseCase/HomeAPIUseCase.swift
  BBus/BBus/Foreground/Home/UseCase/HomeCalculatable.swift
  BBus/BBus/Foreground/Home/UseCase/HomeCalculateUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUsable.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusAPIUseCase.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusCalculatable.swift
  BBus/BBus/Foreground/MovingStatus/UseCase/MovingStatusCalculateUseCase.swift
  BBus/BBus/Foreground/Search/UseCase/SearchAPIUsable.swift
  BBus/BBus/Foreground/Search/UseCase/SearchAPIUseCase.swift
  BBus/BBus/Foreground/Search/UseCase/SearchCalculatable.swift
  BBus/BBus/Foreground/Search/UseCase/SearchCalculateUseCase.swift
  BBus/BBus/Foreground/Station/UseCase/StationAPIUsable.swift
  BBus/BBus/Foreground/Station/UseCase/StationAPIUseCase.swift
  BBus/BBus/Foreground/Station/UseCase/StationCalculatable.swift
  BBus/BBus/Foreground/Station/UseCase/StationCalculateUseCase.swift
  BBus/BBus/Global/DTO/BusPosByVehicleIdDTO.swift
  BBus/BBus/Global/DTO/JsonDTO.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/BBusAPIUseCases.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/CreateFavoriteItemUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/DeleteFavoriteItemUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetArrInfoByRouteListUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetBusPosByRtidUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetBusPosByVehIdUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetFavoriteItemListUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetRouteListUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetStationByUidItemUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetStationListUseCase.swift
  BBus/BBus/Global/Network/BBusAPIUseCases/GetStationsByRouteListUseCase.swift
  BBus/BBus/Global/Network/RequestUseCases/CreateFavoriteItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/DeleteFavoriteItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetArrInfoByRouteListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetBusPosByRtidUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetBusPosByVehIdUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetFavoriteItemListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetRouteListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationByUidItemUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationListUsable.swift
  BBus/BBus/Global/Network/RequestUseCases/GetStationsByRouteListUsable.swift
Labels: 🧱 refactor
